name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Redmine ${{ matrix.redmine-version }} & Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - redmine-version: "4.0"
            ruby-version: "2.6"
          - redmine-version: "4.1"
            ruby-version: "2.6"
          - redmine-version: "4.2"
            ruby-version: "2.6"
          - redmine-version: "5.0"
            ruby-version: "2.7"
          - redmine-version: "5.0"
            ruby-version: "3.0"
          - redmine-version: "master"
            ruby-version: "3.0"
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment variables
        run: |
          case "${{ matrix.redmine-version }}" in
            master)
              echo "REDMINE_BRANCH=master" >> ${GITHUB_ENV}
              ;;
            *)
              echo "REDMINE_BRANCH=${{ matrix.redmine-version }}-stable" >> \
                ${GITHUB_ENV}
              ;;
          esac
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            graphviz \
            mysql-server \
            plantuml
      - name: Run MySQL
        run: |
          sudo systemctl start mysql
      - name: Prepare Redmine
        run: |
          cd ..
          git clone \
            --depth 1 \
            --branch ${REDMINE_BRANCH} \
            https://github.com/redmine/redmine.git
          cd redmine
          cd plugins
          ln -s ../../redmine_wiki_external_filter wiki_external_filter
          cd ../
          cp config/database.yml{.example,}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/../redmine/Gemfile
      - name: Install
        run: |
          cd ../redmine
          bin/rails db:create
          bin/rails generate_secret_token
          bin/rails db:migrate
      - name: Test
        run: |
          cd ../redmine
          RAILS_ENV=test bin/rails redmine:plugins:test
